version: '3.3'

services:
  db:
    image: mysql:5.7
    image: docker.artifactory.mara.local/panbet/mariadb10:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: manticore
      MYSQL_DATABASE: manticore
      MYSQL_USER: manticore
      MYSQL_PASSWORD: manticore
    ports:
      - "13306:3306"

  manticore:
    depends_on:
      - db
    image: deveng/manticore:latest
    command: ["wait-for-it.sh", "db:3306", "--timeout=0", "--strict", "--", "catalina.sh", "run"]
    ports:
      - "8080:8080"
      - "55555:55555"
    restart: always
volumes:
  db_data: {}
